### ISSUE TITLE
ErrorMsg needs more fg/bg contrast

### ISSUE THREAD

**Issue by gangelop** [AlessandroYorba/Despacio#3]
I look at `ErrorMsg` text all day. I need to be able to spot it and read it immediately. The yellowish `#dfdfaf` on top of the red/pink just doesn't pop enough.

**Comment by AlessandroYorba** [comment]
I reduced the font size on my computer to check the legibility and you have a point. All test it tonight using error colors from Sierra and Alduin. What size font do you use normally use?

**Comment by gangelop** [comment]
My font is Inconsolata size 10 in gnome-terminal
![2016-10-13-091529_1366x731_scrot](https://cloud.githubusercontent.com/assets/1893345/19339891/503aac92-9126-11e6-90d8-dd465ad30de1.png)

**Comment by AlessandroYorba** [comment]
How about the Errors with Alduin or Sierra.? Those use the same Error color with a dark grey foreground.

**Comment by AlessandroYorba** [comment]
I usually use a soft red for Errors. Both Sierra and Alduin use cterm=131 primarily because the rest of the colors in the scheme are also muted. However, in the latest commit for Despacio you'll see I took the SpellBad color from Alduin and added it as the Error color. Try it out and let me know.
<img width="1158" alt="screen shot 2016-10-14 at 3 53 07 pm" src="https://cloud.githubusercontent.com/assets/11221489/19404865/63183d74-9226-11e6-9346-36ed535a0cc9.png">

**Comment by gangelop** [comment]
Yep looks good. I think I still prefer the white on red for maximum, eye-assaulting, contrast. But variety is good and I'm still using alduin by default anyway. :)

**Comment by tertium** [comment]
I believe that at least Error and Todo should have non-default, contrasting background. It is especially important for Error, because whitespace quite often gets highlighted as Error (think trailing whitespace or undesired tab characters). I also agree with lathan that you generally want to spot Errors at the first glance at your screen — and the same goes for Todo. 

As for SpellBad and such, a gentle red-on-NONE is probably fine for those who correct spelling as they type, but those who spellcheck after typing might want more visible highlight. On the other hand, non-literary texts would often have non-words in them (identifiers, abbreviations, etc.), and a high-contrast SpellBad would just pollute the text and distract the user. Personally, I'd prefer mild highlight for spelling, like it is now.

Thank you for a beautiful colorscheme!

**Comment by gangelop** [comment]
>  contrasting background. It is especially important for Error, because whitespace quite often gets highlighted as Error

Indeed. I hadn't thought of this. Easy example: put some whitespace in the second line in git commit message (and also some text in 1st and 3rd line). In this example vim uses `Error` highlight group, not `ErrorMsg`.

**Comment by AlessandroYorba** [comment]
good feedback! @lathan @tertium 
The changes are in the latest commit and they are default for despacio and despacio_Twilight settings
New Todo Highlight: 
![screen shot 2016-10-20 at 2 26 37 pm](https://cloud.githubusercontent.com/assets/11221489/19578735/e69f2de2-96d1-11e6-844f-16d01ceb3536.png)

New Error Highlight:
![screen shot 2016-10-20 at 2 26 57 pm](https://cloud.githubusercontent.com/assets/11221489/19578752/f980f990-96d1-11e6-9226-a7cbc3882cb0.png)

New ErrorMsg Highlight:
![screen shot 2016-10-20 at 2 27 31 pm](https://cloud.githubusercontent.com/assets/11221489/19578757/ffa028f0-96d1-11e6-8b06-0ab67f087f2a.png)

**Comment by gangelop** [comment]
:+1:

**Comment by tertium** [comment]
Great, thank you!

**Comment by tertium** [comment]
That's perfect, thank you!

**Comment by ghost** [comment]
I'm going to go ahead and be nonconstructive and say, the new error colors make me cringe. It's such a perfect theme otherwise... But every time I open a technical markdown file, I'm slapped in the face with this jarring red. It get that it's supposed to 'pop' but from a productivity standpoint I fail to see how someone would struggle to locate a more subtle red. Please consider making it sexier.

**Comment by AlessandroYorba** [comment]
@tertium @dawnofthedev @lathan 
Right now it's Scarlet:
"Scarlet        160      #d70000      http://www.colorhexa.com/d70000
<img width="141" alt="scarlet_160" src="https://cloud.githubusercontent.com/assets/11221489/19989833/71491966-a1e6-11e6-9d73-23d6b000c9f7.png">

Here are all the color options for Red using 256 color space. 

Other Option
"Firecracker    131      #af5f5f      http://www.colorhexa.com/af5f5f
<img width="139" alt="firecracker_131" src="https://cloud.githubusercontent.com/assets/11221489/19989860/9a86e600-a1e6-11e6-853f-de205558c139.png">

Other Option
"Cherry         196      #ff0000      http://www.colorhexa.com/ff0000
<img width="145" alt="cherry_196" src="https://cloud.githubusercontent.com/assets/11221489/19989872/af40edca-a1e6-11e6-982a-fd69939d1fe7.png">

I recommend Rose, because an Analogous Color to another color ( Oak ) used in the theme : 
"Rose           167      #d75f5f      http://www.colorhexa.com/d75f5f
<img width="142" alt="rose_167" src="https://cloud.githubusercontent.com/assets/11221489/19989867/a506688a-a1e6-11e6-99b6-3b17f26a9d4c.png">

Thoughts?

**Comment by AlessandroYorba** [comment]
@tertium @dawnofthedev @lathan 
if you are interested in testing the Rose color, try adding this in your .vimrc to override: 

``` VimL
colorscheme despacio
if g:colors_name == "despacio"
autocmd ColorScheme *  hi! Error    ctermfg=167 guifg=#d75f5f ctermbg=233 guibg=#121212 cterm=reverse gui=reverse
autocmd ColorScheme *  hi! ErrorMsg ctermfg=167 guifg=#d75f5f ctermbg=NONE guibg=NONE cterm=NONE gui=NONE
endif
```

**Comment by tertium** [comment]
The main thing that I advocate for Error is to be something-on-red rather than red-on-default. I can understand @dawnofthedev when he finds the Scarlet background to be too garish. The Cherry would then be even more so, and the Firecracker seems to be too dull for me.

Rose looks very good. 

(By the way, is there some reason for defining it like you do, with cterm=reverse, rather than "ctermfg=233 ctermbg=167 cterm=NONE"?)

**Comment by AlessandroYorba** [comment]
@tertium IDK. I could be wrong about this but I think that Vim by default uses cterm=reverse for Errors, but you're right.  I imagine that one could simply write it as "ctermfg=233 ctermbg=167".

**Comment by AlessandroYorba** [comment]
Latest Commit now has a new Error and ErrorMsg
<img width="686" alt="screen shot 2016-11-03 at 6 49 06 pm" src="https://cloud.githubusercontent.com/assets/11221489/19991838/43cabc78-a1f6-11e6-956c-1015955332bd.png">

<img width="632" alt="screen shot 2016-11-03 at 6 49 19 pm" src="https://cloud.githubusercontent.com/assets/11221489/19991844/4975f34a-a1f6-11e6-9206-6e8024b69a6d.png">

**Comment by ghost** [comment]
@AlessandroYorba Rose looks great to me. I encourage you to use it for SpellBad too.

**Comment by AlessandroYorba** [comment]
Thank you everyone! This issue is now closed
