### ISSUE TITLE
Search contrast

### ISSUE THREAD

**Issue by tertium** [AlessandroYorba/Despacio#9]
The Search group, also used to highlight the current line in the quickfix window, is currently Bluebells-on-Dune which I find hard to read. I would suggest ctermfg=234 (Twilight), the same foreground as for Diff(Add|Change|Text) which also have a bright background.

I keep pestering you about the contrast issues, sorry for that :)

**Comment by AlessandroYorba** [comment]
@tertium It looks visible to me but I can see that it might be hard for some users at smaller font sizes to distinguish the foreground. I like your suggestion and I'll push the change but perhaps the culprit is the background color.  I'm curious what you think of this: 
Try a default search and then 

``` VimL
:hi Search cterm=reverse 
```

Let me know! Thanks!

**Comment by tertium** [comment]
I like cterm=reverse quite a lot. For the quickfix window, Dune-on-Bluebelles is definitely better than Twilight-on-Dune.

**Comment by AlessandroYorba** [comment]
Done! Try it for a while. Thank again!

**Comment by tertium** [comment]
I'm quite happy with this setting, thanks a lot.
